### ISSUE TITLE
Error validating installer data

### ISSUE THREAD

**Issue by ubayebx** [mkslzk/Y50-70-Hackintosh#2]
Can you tell me what happened whit this, i try your latest EFI but still same result
![IMG_20210107_021222](https://user-images.githubusercontent.com/17410794/103810552-038bbe00-508e-11eb-9557-d94c1951daad.jpg)

**Comment by mkslzk** [comment]
Hi 
Try to use an other recovery image. EFI works.

**Comment by ubayebx** [comment]
Solved thank you 👌😁
